CREATE TABLE IF NOT EXISTS students (

    id SERIAL PRIMARY KEY,

    student_id VARCHAR(20) UNIQUE NOT NULL,

    fullname VARCHAR(100) NOT NULL,

    department VARCHAR(100) NOT NULL,

    level VARCHAR(20),

    barcode VARCHAR(100) UNIQUE NOT NULL,

    photo VARCHAR(255),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);